  
export var AppKey : any = 'vtexappkey-dipicomx-NWVUWO'
export var AppToken : any  = 'YHAXLTUYGTKKJIQMVVAORRVJXEDVOSIGYGWJNKHXFUFUSBZIIMYPERRHMRZHPZJNKELCLHYKODJXLBQWEUMCUTBGPOXWLZHGKSKNPXWBOOABIUVKACDVMHSQDENWKBZO'